### ISSUE TITLE
Support for Out of band swaps

### ISSUE THREAD

**Issue by checketts** [esmiralha/express-htmx#1]
Does your library offer a way to render multiple templates so OOB-Swapping is supported?

Example:

```html
<div>main content</div>
<div id="sideThing" hx-swap-oob="true">Other thing</div>
```

That will put the 'main content' as usual, but also locate the `#sideThing` somewhere else on the page and swap it out.

**Comment by esmiralha** [comment]
It does not deal at all with the rendering part of the backend and it makes no assumptions about the rendering. In any case, if you render the template with the proper htmx attributes, then OOB swap will happen as expected.
